package(default_visibility = ["//visibility:public"])

py_library(
    name = "spark_functools",
    srcs = ["chain.py"],
    srcs_version="PY3",
    deps = [
        # requirement('cytoolz'),
        # requirement('pyspark'),
    ]
)

