package(default_visibility = ["//visibility:public"])

py_library(
    name = "pytest_helper",
    srcs = ["conftest.py"],
    srcs_version="PY3",
    deps = [
        # requirement('pyspark'),
        # requirement_dev('pytest'),
    ]
)

