package(default_visibility = ["//visibility:public"])

py_library(
    name = "spark_autopatch",
    srcs = ["__init__.py"],
    srcs_version="PY3",
    deps = [
        # requirement('cytoolz'),
        # requirement('pyspark'),
    ]
)
